name: CI
on:
  push:
    branches:
    - main
    tags:
    - "v*"
  pull_request:

jobs:
  generate-native-container-launcher:
    name: Test and upload native container launcher
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
      - uses: coursier/cache-action@v6.4
      - uses: coursier/setup-action@v1.3.0
        with:
          jvm: 8
          version: "2.1.0"
      - run: sudo apt-get install -y nailgun
        if: runner.os == 'Linux'
      - run: .github/scripts/maybe-with-graalvm-home.sh nativeContainerTests
        shell: bash
      - name: Copy artifacts
        run: .github/scripts/maybe-with-graalvm-home.sh copyContainerLauncher artifacts/
        shell: bash
      - uses: actions/upload-artifact@v3
        with:
          name: launchers
          path: artifacts/
          if-no-files-found: error
          retention-days: 2

  upload-launchers:
    name: Upload launchers to GitHub release assets
    needs: [generate-native-container-launcher]
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: true
    - uses: coursier/cache-action@v6.4
    - uses: coursier/setup-action@v1.3.0
      with:
        jvm: 8
        version: "2.1.0"
    - uses: actions/download-artifact@v3
      with:
        name: launchers
        path: artifacts/
    - run: ./mill -i uploadLaunchers artifacts/
      env:
        UPLOAD_GH_TOKEN: ${{ secrets.GH_TOKEN }}
